userDeployments:
  enabled: true
  deployments:
    - name: "software-releases-dwh"
      image:
        repository: "eu.gcr.io/mrdavidlaing/software-releases-dwh-dagster"
        tag: latest
        pullPolicy: Always
      replicaCount: 1
      dagsterApiGrpcArgs:
        - "-f"
        - "/dagster_workspace/pipelines.py"
      port: 3030

runLauncher:
  type: CeleryK8sRunLauncher

rabbitmq:
  enabled: true

dagsterDaemon:
  enabled: true
  queuedRunCoordinator:
    enabled: true

extraManifests:
  # Set default container resource requests/limits for the namespace
  #   * To override these for dagster system containers; edit the resources sections of
  #     this values yaml -  eg: dagit.resources & celery.resources
  #   * To override these in solid execution containers; add a @solid(tag=) similar to:
  #      { "dagster-k8s/config": { "container_config": { "resources": {...
  - apiVersion: v1
    kind: LimitRange
    metadata:
      name: default-container-resources
    spec:
      limits:
        - default:
            cpu: 250m
            memory: 512Mi
          defaultRequest:
            cpu: 50m
            memory: 256Mi
          type: Container
